# wrangler.toml

name = "stock-analysis-project"
main = "src/worker.js" # Cron Trigger를 처리할 메인 워커 파일
compatibility_date = "2023-10-30"

# Cron Trigger 설정 (매시 45분에 실행)
# 미국 동부 표준시(EST/EDT)와 한국 시간(KST)을 고려한 UTC 기준 시간입니다.
# cron = "분 시 일 월 요일"
[triggers]
# [夏令時] 10:45 PM KST ~ 6:45 AM KST -> 13:45 ~ 21:45 UTC
# [標準時] 11:45 PM KST ~ 7:45 AM KST -> 14:45 ~ 22:45 UTC
# 두 경우를 모두 포함하도록 넓게 설정합니다.
crons = ["45 13-23,0 * * 1-5"]

# D1 데이터베이스 바인딩
[[d1_databases]]
binding = "DB"
database_name = "analysis-history"
database_id = "9d3b6822-bded-47bd-ae0f-bf1b6baf229f" # `wrangler d1 create` 명령어로 생성 후 채워넣으세요.

# KV 네임스페이스 바인딩
[[kv_namespaces]]
binding = "TICKER_KV"
id = "your-kv-namespace-id" # `wrangler kv:namespace create` 명령어로 생성 후 채워넣으세요.
preview_id = "your-kv-preview-id"